---
title: "First Knit"
author: "Melanie Vera"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended Highland High School and I did graduate. I just graduated in June. I am better at Math then English, I hate English because I don't like writing essays. Also, I feel like they give more work for English. I would have to say it would be math or history. they are just easier classes and are just more fun.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   I don't have a computer, but I have an apple ipad. I would have to say, maybe like a 6 or 7 to knowing about computer stuff. Sometimes I know somethings really well, but other times, I am completely clueless. I have great internet access where I live, so accessing things should not be a problem.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   
 I prefer to be called Melanie, but I am also fine with Mel.




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   I want to be a nurse practitioner. I think I would be interested in anything biology. I am trying to acheive my masters degree.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   I have only gone to Mexico, but I would love to travel to other places as well. I would really want to go to Italy, Monaco, France, Korea, Japan, Dubai, an Hawaii. I have never been in the military, but maybe I would go to the AirForce, I would want to fly a plane.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 I am taking Math 115. I did not know that about Math 116, that is good to know now. I would need to attain an A to get into the nursing program.






  




